networks:
  backend:
    name: backend-network
    external: false
  frontend:
    name: frontend-network

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind #addr:58.65.321.5
      device: D:\docker\data\mysql_data_volume


services: #container
# docker run --name:db -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=bob -e MYSQL_DATABASE=wordpress 
# -e MYSQL_USER=toto -e MYSQL_PASSWORD=toto mysql:latest
  database:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PWD}
      - MYSQL_DATABASE=${WP_DB}
      - MYSQL_USER=${WP_USER}
      - MYSQL_PASSWORD=${WP_PWD}
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql

  myadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PWD}
      - PMA_HOST=database
      - PMA_PORT=3306 #pas obligatoire si la base écoute en 3306
    networks:
      - backend
      - frontend

  wordpress:
    image: ${WP_IMAGE}
    container_name: wordpress
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=${WP_USER}
      - WORDPRESS_DB_PASSWORD=${WP_PWD}
      - WORDPRESS_DB_NAME=${WP_DB}
    networks:
      - backend
      - frontend
    volumes:
      - D:\docker\data\wordpress_volume:/var/www/html
    